---
language: bash

# Tell Travis to start Docker when it brings up an environment.
services:
  - docker

env:
  global:
    - secure: "PX/+o75m7EJI32c4B90ApJvfZd4b8WA/hCsqkD9KJj4RacwliEhpF2qZAOVfwCFh09xcbbv9W6WhIjf/Pbb1KoM4pDtxeiUiVDvC1whFFw0r+JrWafssTzMlvjvrY3UaUex+T19UxABTsXx/VEfAXKa654JWrWy/ja6lI+c8Dq0C3pvigHsYjK1ZSVqJ4oBDlHDc92RD1uzODND1u50PVT2hLyfMqPjrPtzZlXdvo7fZD6qZ4TS7wgpX/QQ4l51gBVEtBL1URZjSgRh24ivbPxMQzV/2B82fyYwDqG7Jq9KTvtR3sT+gOxarNoLNDd5eXWKP3dIiVj92dXnsHkQl7XTZ9N/8RNWZ1lgwfcBAOx2cIes2w0FPmo0ctbTSmN70MzABv2ujHJpObwa0u8EYiPyWq6ZK8HmSLla0wVyGH/zbHGd5Jr2aijPhuJ04WCf4BWJ50LV+uZr0QMA/AhMDBPlZjS6iLLi75Pqn5MSnGTMbnhf3RuMr+JEZ4GTmuu1/fqitRK5o6dpfV9TTtzUpZrifK5Ji09YIqbHQDk6I2d/+VkN+ilgQE8hT3Xv7gM+mV6fPXtSlmgxtjmkHDBL//CAmq6Yy3KHWw9OYjnq5WhQn3SR+1x9mb5S2L3mnHXoMIPECsc+WFeMpmOTGDon77mE7KVklX+Lx3Nmc0hTkdps="
    - DOCKERHUB_REGISTRY_USERNAME="wolvverine"
  matrix:
    # Provide a list of GLPI version to build
    - GLPI_VERSION=9.3.2

script:
  #
  ## Build
  #
  - ./hooks/build

  #
  ## Run tests
  #
  - ./tests.sh && ./hooks/push
