dist: xenial
language: bash
sudo: required

# Tell Travis to start Docker when it brings up an environment.
services:
  - docker

env:
  global:
    - DOCKER_REPO=wolvverine/docker-glpi
    - secure: "RMyMKLKryKv9dSO3waygM+mj5UozDcUeZmh8RbiOF7FGD26miwPErQhdpouuLJaXen5/ypmBdK6/FRdGPRyusUxym0DpkMtzSwQ96cgOGo7HIg/zXAUd5Zm/LWawd/Rxj4/j+uc4IoF0o7XUY8K7WxLdE2QXp7tSDnfiKS3IjvoNxhtHrSNBZEMTMyuLIzqjR9ITuJ+de7lfy/FfASlHdCibyFMfIukv+WCJhz9N6PYwWn/higjf+mSdK/1UNgz64RVQSrKNjjv2bS52qG9wH6lDwJdc5bWyuN75hMZmASHdrybRd/9A/u8T7kieK5qmu+eRDgy807byYGSe8xBAHY+rONXHzKaZwtpUdzLPPQjMJ6cB4h7pQOIge2UpaHfy/9vor6AGzanhguG+jfDDNlbOTWtq2mW50e1vTPvwNdpwQgML112vFUKRwk/Ygsr9LHdTIL+fBSzyrfS6VJ1rpXYYaqbPCG2BzPcS1ADynjpa4xdB8OYrqbcUd6Bci4w0azrvNFn51GJGkSEip6RISh7m21MfWFOxcYCWZmgxnevT+xgdrtvy2zusKnD7WNnKBtm6o7EOS31Gjpbm3Yh6JiUuAPAgM/Gwm5CQHSFf1oCfiO3UdBFagt1cyCHWOZwEmwHF4qjUYPl7JKz6MCHQUQUZgxKu0ALZT2Owij3m/IY="
    - secure: "RfqYGETAos+Ek3Yru2lwjA5mKcjsgSOI7rUSNVKc5Mnkh2UZ3TOXSqa9wu/Z5ttquoXvH6gb12C9tRS37qegQnCfaKBiH43k8BKNxijA8EV9r2wVUVzRxN9+MgKGbvJrkq/Ma2TBIj5EfdxVMYHuYY4wcL6dxZYcUk3DGsyZ3+gB8yRo1jDzsaBm2l5VAJnX6IqeF3ZR+2ITHVSqb1zLzSAlGv0/095T9MD5cCrU3f1Q5vT1ghRgq4QDnkBTOjvYIlWOyM/Qdc0HKo7C9WxH5hw6g30fI/DQkxSBt4kB7RDm3BWASJamXN9YDf0yUisv8vbXpW7Dqq4R2wdNHBqOeeQATHEGS1iHlsa63vFM+QvLRKIpiYU5zUJIj5rynaO61HWfTxm9UnCbcxpIaFLM5K5UKKFpa4+8Wma/zqIYvEi5FI295StxyrcfdfFb93Nfcwl8/P7rlUna5U1PWXphGV23zCECDuHxAVYtRHXEFa3bVCE2Izl/rg6X65WZPoT7nNojzPIFbxBCe3lZYZduC5+jJti5Xuu12cEEzsanc+o8faxkJZwaGyX5wImCDHotD3MvhwYfgTV/3DnuwF3CMx5yfh6K8jYYSCb8FOdyFWYnf3umR7gQ7350bgtnYnZYFAhNx8DlNCiDHdH6mpDml00IDRyT+j0ss5BHxqt1EXs="
  matrix:
    # Provide a list of GLPI version to build
    - GLPI_VERSION=9.5.6 IMAGE_VARIANT=nginx-72 UPDATE_README=1 UPDATE_LATEST=1

before_install:
    - sudo apt update
    - sudo apt install -y shellcheck

script:
  #
  ## Build
  #
  - ls -l
  - ./build.sh

  #
  ## Run tests
  #
  - ./tests.sh && touch _test_ok

  #
  ## Publish
  #
  - '[ "$TRAVIS_PULL_REQUEST" == "false" ] || exit 0'
  - '[ "$TRAVIS_SECURE_ENV_VARS" == "true" -a -f _test_ok ] && ./publish.sh'
