dist: xenial
language: bash
sudo: required

# Tell Travis to start Docker when it brings up an environment.
services:
  - docker

env:
  global:
    - DOCKER_REPO=wolvverine/docker-glpi
    - secure: "S7PIcphfpLTTl4DB5rh0uNDqNiJtJ3BK8qaqOaFuPScCxqNqe+5qhCGserNMm6uyfuTY2pclsLg3Ccqxjnb1EzpnRVv3q5Gdo24jlGEgtXDtrYUWw59SuTGZ+j7So1WG39fdZYdQ7OJwDTAMCdIYbWVOSV0sgw6wI3VLNn+zPoTJNXoLCyNDnB+qEvTVkZ3uwhZhQvmF4BttGnw5rSGPElbbl2zV2EzPaScuXkmD9oXKl0rtB1w/dbBe5CNq7HAAZo0FcJqKWcuYH1RbezX8qJyv/AUlmPxaB9XRjaVs7iHFvGWbfuHP3sbRaDFyZB1XPYdjkrtEzD3js0kTOiOE2IQfY97dSyXm0s+9XU7DJ05FG1rIWODO7EKg6aXak6japJQLEwRS8umh6KlA1JTgi3kmMdL2tdYbJVJYPzkYsWQcRGcGLJbvlspFlyw3M0mFsEgNiSdlAg7oeeuveF1hkR8adfl2wrUhR/bOISpVLsFnUMJRKdEs3VMpC+YZiNHnoS+XpFu/Pag3St+wHhycw5k5qfp0Ue7ca32FBNPc7BlZduiCG3dvIfdUdC8+mSQbwUkG5C/NfcgKA/JpeZvJyqIVNtEtEvAY1lqB/izKOxgpjk2HwPggGMczYj07BbdEp5R/oRlOcGDO6LM0/zL23ds5lCvlE2wWpbmB9m+5wAk="
    - secure: "RfqYGETAos+Ek3Yru2lwjA5mKcjsgSOI7rUSNVKc5Mnkh2UZ3TOXSqa9wu/Z5ttquoXvH6gb12C9tRS37qegQnCfaKBiH43k8BKNxijA8EV9r2wVUVzRxN9+MgKGbvJrkq/Ma2TBIj5EfdxVMYHuYY4wcL6dxZYcUk3DGsyZ3+gB8yRo1jDzsaBm2l5VAJnX6IqeF3ZR+2ITHVSqb1zLzSAlGv0/095T9MD5cCrU3f1Q5vT1ghRgq4QDnkBTOjvYIlWOyM/Qdc0HKo7C9WxH5hw6g30fI/DQkxSBt4kB7RDm3BWASJamXN9YDf0yUisv8vbXpW7Dqq4R2wdNHBqOeeQATHEGS1iHlsa63vFM+QvLRKIpiYU5zUJIj5rynaO61HWfTxm9UnCbcxpIaFLM5K5UKKFpa4+8Wma/zqIYvEi5FI295StxyrcfdfFb93Nfcwl8/P7rlUna5U1PWXphGV23zCECDuHxAVYtRHXEFa3bVCE2Izl/rg6X65WZPoT7nNojzPIFbxBCe3lZYZduC5+jJti5Xuu12cEEzsanc+o8faxkJZwaGyX5wImCDHotD3MvhwYfgTV/3DnuwF3CMx5yfh6K8jYYSCb8FOdyFWYnf3umR7gQ7350bgtnYnZYFAhNx8DlNCiDHdH6mpDml00IDRyT+j0ss5BHxqt1EXs="
  matrix:
    # Provide a list of GLPI version to build
    - GLPI_VERSION=9.5.6 IMAGE_VARIANT=nginx-72 UPDATE_README=1 UPDATE_LATEST=1

before_install:
    - sudo apt update
    - sudo apt install -y shellcheck

script:
  #
  ## Build
  #
  - ls -l
  - ./build.sh

  #
  ## Run tests
  #
  - ./tests.sh && touch _test_ok

  #
  ## Publish
  #
  - '[ "$TRAVIS_PULL_REQUEST" == "false" ] || exit 0'
  - '[ "$TRAVIS_SECURE_ENV_VARS" == "true" -a -f _test_ok ] && ./publish.sh'
