dist: xenial
language: bash
sudo: required

# Tell Travis to start Docker when it brings up an environment.
services:
  - docker

env:
  global:
    - DOCKER_REPO=wolvverine/docker-glpi
    - secure: "RMyMKLKryKv9dSO3waygM+mj5UozDcUeZmh8RbiOF7FGD26miwPErQhdpouuLJaXen5/ypmBdK6/FRdGPRyusUxym0DpkMtzSwQ96cgOGo7HIg/zXAUd5Zm/LWawd/Rxj4/j+uc4IoF0o7XUY8K7WxLdE2QXp7tSDnfiKS3IjvoNxhtHrSNBZEMTMyuLIzqjR9ITuJ+de7lfy/FfASlHdCibyFMfIukv+WCJhz9N6PYwWn/higjf+mSdK/1UNgz64RVQSrKNjjv2bS52qG9wH6lDwJdc5bWyuN75hMZmASHdrybRd/9A/u8T7kieK5qmu+eRDgy807byYGSe8xBAHY+rONXHzKaZwtpUdzLPPQjMJ6cB4h7pQOIge2UpaHfy/9vor6AGzanhguG+jfDDNlbOTWtq2mW50e1vTPvwNdpwQgML112vFUKRwk/Ygsr9LHdTIL+fBSzyrfS6VJ1rpXYYaqbPCG2BzPcS1ADynjpa4xdB8OYrqbcUd6Bci4w0azrvNFn51GJGkSEip6RISh7m21MfWFOxcYCWZmgxnevT+xgdrtvy2zusKnD7WNnKBtm6o7EOS31Gjpbm3Yh6JiUuAPAgM/Gwm5CQHSFf1oCfiO3UdBFagt1cyCHWOZwEmwHF4qjUYPl7JKz6MCHQUQUZgxKu0ALZT2Owij3m/IY="
    - secure: "D6sOV8APuMbKZ+71YEzot9vQXMNYNp81c6xCm35CGBocAot+/zTUoTzMcIqBTLe1qrEKp3/2PghbrJ5a3yAvsKmeiuSQF3CnQIWhweULMXh2AQ1YeqM/1I5osWrqYVmE0CFmhWPPK28L9LYTtysB1KJ+ZC5IqocAZ1K3pzDXaF3tWu0GEi+OPGxQUuDUIQC2JQriVTyCb9DTsa7stP0KA+TFtn9gLcW/PRFIWoaaFPAgcn9DVNiejSYerGEuSbKYdJSZQ/i1DeUOxHjMM0oO0R4hC2c0d4pw0kvOfUGkHXNT63eS8GYRm5woV2CqmXJcSz0xN0MQGKLI5tKPaUEHY3csbs/H24cloPH01t/y+MzbzAPUf16frgDkD39kgZr0HDWdBfxHIR0sTIZ1fqqgq6NQdzqFfNetzKjw1Tz2J/ChM2qNF8dQbnAkk2fc5efGxX9ADazQXsKcsVvZFIXBECO8XkkTVJK8MDt+Rt7k24QCi7RHWWQkJbCZ2O9o1oYpDzO6shG8tjFisL5syL2pG+fbUyq1xBwyeHWGrSF+ClBTe8d8mqiI2124WH6g3DEGaOpW++ng9+FNY7hQJXcWtlaW4NWpA0Od2ew5M5l/X+ZKmzl12myXV+XrVVD3eftR0FWzIyDYXezAr2hwHIFFwWdG/Vinc8+0XBskgy411+c="
    # READ!!! https://docs.travis-ci.com/user/encryption-keys/#note-on-escaping-certain-symbols
  matrix:
    # Provide a list of GLPI version to build
    - GLPI_VERSION=9.5.6 IMAGE_VARIANT=nginx-72 UPDATE_README=1 UPDATE_LATEST=1

before_install:
    - sudo apt update
    - sudo apt install -y shellcheck

script:
  #
  ## Build
  #
  - ls -l
  - ./build.sh

  #
  ## Run tests
  #
  - ./tests.sh && touch _test_ok

  #
  ## Publish
  #
  - '[ "$TRAVIS_PULL_REQUEST" == "false" ] || exit 0'
  - '[ "$TRAVIS_SECURE_ENV_VARS" == "true" -a -f _test_ok ] && ./publish.sh'
