---
language: bash

# Tell Travis to start Docker when it brings up an environment.
services:
  - docker

env:
  global:
    - secure: "s6N14mGTrrfGTh3e0xD4YvnDWul/5r/zShoJjuzfs1ddyz8XuEDurVM4snqhV3mOYpL/e+oKXyY0SPRZt34brY0xrNLwtf3VcbgOg0aPY8olLzYK60+q+AGqCaICH6XUrPU3u07df+zEFNKKWwIA5M1hnFHU25uFjGuJ0FwcdJgN42hXUob8nSkhn2qP+Qy1G62pDUol3Ir01oPLUAd5W/FWgqnessscFc6jozfImMknxhCNp6unPGxlyKmo5vNsD/dmVVy1imUjwThd8CWHIyuy5SJlA3m/PVRvudgQj+3962RZhHJrpYrrsuXKDFbvowGx/i6hYYUBLgQWCsF6CApXLzQEULO4wynz+l5N3pBLADBdGR6AeOnAs4q3BTnz3F+CllYdp1ok0jDNn+c9KwFOBQyDPJjVb1GgbjxksDCSONeJHuwgpLBn6o497Qc2DOy/cFq82nQdxAAIf4TBYX2O1Ofu6mdIlY1TrTcSYLe+2qerTkdGIeuE/laefHSkQqgHBsafqsvXuZCzBY35l6pfhJzIzn6hGm3l0ygL85nQMeJgXgpo3/re/9ha9SfeeCzJj2q+vGt7T0Db/oy6TtTndfaiKELNU2lrpQzTS1XSFXxHfg30mpm9coJk9nNRTSUJ+mD9jC5t68IfjfY81PxEiaUKIXz96Uek4ipSx/c="
    - DOCKERHUB_REGISTRY_USERNAME="wolvverine"
  matrix:
    # Provide a list of GLPI version to build
    - GLPI_VERSION=''
    - GLPI_VERSION=9.3.2

script:
  #
  ## Build
  #
  - ./hooks/build

  #
  ## Run tests
  #
  - ./tests.sh && ./hooks/push
