---
language: bash

# Tell Travis to start Docker when it brings up an environment.
services:
  - docker

env:
  global:
    - DOCKER_REPO: turgon37/glpi
  matrix:
    # Provide a list of GLPI version to build
    - GLPI_VERSION: ''
      IMAGE_VARIANT: nginx-56
    - GLPI_VERSION: 9.3.3
      IMAGE_VARIANT: nginx-56

script:
  #
  ## Build
  #
  - ./build.sh

  #
  ## Run tests
  #
  - ./tests.sh
