---
language: bash

# Tell Travis to start Docker when it brings up an environment.
services:
  - docker

env:
  global:
    -secure: "siupzkJOMBRdtT29oKgx8cEZJZtIlXZYlLSr7vTUTDzLJ0Jci66ysUqtHB9NclU7zmimSzhweSBPDk1VSgcTZX+6jV1dpOg+hrcrKBt3sOM4k6nzn0AdAEvlF2cGhfxH+KfaeT8CBRIWwXg3xOHiK6hc/ajgnc8wlqlbNfAcp2QuI9O+R+BJqBwn+qadg39qMP45dc6dD+eH417352uelMSULpOQdkls/RFSlkcTFeOxJZjd6IKmWh6QLws0pbJsoC2nsH8M71VW+MD1Xk8ae4bLGsgvy2t1v+jcnr3mIUbiVattJESPnVirit/wtiEaLcXBt1rBbxCUAFYRiErN1te18ChVMP5QFoSh9sxXCG/N1OOD8OwiBd16MDXFk5iISXDRtT3kfJPHR9k3kETEEDU934Biag9jLYjY95Q21QVObxnR6HjIZkZz2kluv78/oeTCqmdVXO0PiAHfwjVxWeIEdKLKbssC4dBS/3XSxQoXM5K+/RD4dL1D51Udv3C0alqQaqvVE1EASbV4lRQgFTRyFXL0pcAm7/X2fr4MBzW3ubD/j3L++dR4jmBsfLhRMPhLnR/zpCbh09WVD4Aay2TiWSIinORDv2amzFPNhQqc+KmCgUoYSWbi0FmZlE63ZvojJcMW4D39ddhS18UZGG8MLh4zDg+Ein0Vh/vHehc="
    - DOCKERHUB_REGISTRY_USERNAME="wolvverine"
  matrix:
    # Provide a list of GLPI version to build
    - GLPI_VERSION=9.3.2

script:
  #
  ## Build
  #
  - ./hooks/build

  #
  ## Run tests
  #
  - ./tests.sh && ./hooks/push
