---
language: bash

# Tell Travis to start Docker when it brings up an environment.
services:
  - docker

env:
  global:
    - secure: "RvGa39L/1O9pDJtApBUGpnLw/I/2gNRd1yLx8YFruBLJxEVjjsHWHxqkJDVjj6Es0CO4BUdt2xUz9WadtZ25c+dNHDpL+KKz0lFedt5EZvWLhQ7hZInNpQ3MuaRR2ngzL/whXnt9YP7tkLE8UBdyC+Dir7ugml/KSPcRYR9lYVzQVLQ6GzsbUrpJMHh+cc3qoZZq03NQPmW7GPk6quP8sgLcBHTRmQYDKnepMPVcH6/qiDdTthYynic4dCktwQuGPNvAEBcD/WZDTR13L8Ksx+VqyiqCNxoP6Tlkz+mg+QYv1PbyLFl0EXPGuyTJ/dvx3S5c9DGvI2QeaT6tFTXyL48zxM6xlO79klAQCHLq9fc/vYGlTtSTKmPNDV4ucE8twVIUbGCy9CYyxeD+PTT8xvH0fwQNC4ZyhQL/ebi3LaKs80s/JyC1g09VPN7p2pkScQ6f1XUNQtJCL0Rbsjkv/V6CaFF46MRtK6QIqbOcmPF84OC20gfrCbZoiRYgwtzREdf07J8Sj0Cccz92K9fD/oiXjevlhAVVa2I2TFnzNGjV4yXizAf9ooeWjr5rIT8mbXQopfYKtOCoOFx4mCw+RvUhKUTfJajnW2kdWcGGBHhjmpD2OjHnP8eC9DbvwCa0uH0wx7YmnON8PysW7kFJaQAD/YQagolaVo3+Cfk47JQ="
    - DOCKERHUB_REGISTRY_USERNAME="wolvverine"
  matrix:
    # Provide a list of GLPI version to build
    - GLPI_VERSION=9.3.2

script:
  #
  ## Build
  #
  - ./hooks/build

  #
  ## Run tests
  #
  - ./tests.sh && ./hooks/push
