---
language: bash

# Tell Travis to start Docker when it brings up an environment.
services:
  - docker

env:
  global:
    - DOCKER_REPO=turgon37/glpi
    - secure: 'AgdUC6iQJtb1+1A4wgIYMMDGWGWZ3sy+OIwSaJ91D6hKyFfkPTNBs6Ffrc+DrGwFttC9PohGGoU3BhDd6nBYaLC69CWK1neb8Rg3vQC/vYbdxDtI/e2Pi9Xg0D39yFqaadfFmWgUNHrPe0uwF3BfI9yGvUk/giAKyWOSi/tKcPeoOZpXj6VhCESdlim1XC7vKJ2zvHx6IAJcadUe74d4IZpLsAKegid5gPy0Dvbo8HAMlIO6MR2knzJB1Yv3UM+6+l6Zwxec73qC2MtFTr1umrxw38ABzXF+ZPlMHPGT0cl6PZ9xMWpRKyKDlzLpE+78yW+/UYdGvb/hx3Wm2VFdBUCciwOHew1EPEy/UK/1909V0R6uIRdf3wclBAhj9XAP73EhcshV35qw8QHoPmRtfdfkMZ4EttwusNZVIDVE2CJoqGtO6DsdSOWG1egh9TdlvqGWt8VHaXwW+nsfOrfChbo6JILw1ca0VEc54l9OLjbVGqBXekLjPrcS9gw0KZDNGJO3JIbn5lKGY51c7xJwgsCWZAPOqCtkI8KPLZyu5aMUTfhLkFZ5VT+RQDRoBQeZi1Ul4YNPmywM7vZCFvtcUHNJ4wUEyucZT6cKYgSu7dVLwmVtVwUdkg6vqnpFFXsRM2lOukBGyeZ68yk3196XrrvP/CUGf0I1CedGNdRI6ws='
    - secure: 'FkVH1Vl3IHDlNdxORwCRAeoIUVVIFbEYAWQSlZC+cjGivh/CDVrXNudnhOpPktkG1txs/6D7swydmRlOyUKOEzaW/JSlBNw9BAzI6FEXZlQ77ylnfVxbQG5bJUgUmYpGFabwEH4vn0c+yxlgvWcX+6fb1iKGt7FNdbNDdPXglmVBKmTmRlQK5p9r6wlaWCPwDgwIS5KuSdNcXmlEZj57hKAKyhCvMCONbLKDVwX6U95BlQENGYzkQ0Og6UX0Eud2o5PaKpJ19rgdR4vTuu5zQ8m4q3xjSG5IMaupjMVqoaQPKkEiFrWI7GjIrjU67f+31qOAvxAAqdRnr/k6pOsY9XQ1NX0NVBHCtzYIvtbqF4ZNVFP5TsRRMtz/WKZKVTcocFw0so2VzGttxxkNMYXw9gmM8AzHihMuSKA9ZzB1EGdxY9fpPcoUNMbMyK0KmBeCGKNyECdKOEJ2n2V8Kt6Ig1jrV5kAEXXwI3Unwe9vgZ4MmHg4UjugYDFeRTwasITZi4ykPsLNk+tqvHOUgm/jrOIx/PAeZOD5yzC7sV/nt4Qb+FBeUXZE+1v/bz9iB1uSeIP5WGpEuOwexleTqsdp9469/aNRFIlAszbj7uIWJdWpv3abaw3b35TudBuIWv/iaUDvs3RJaicEey5HeYBEiyPjilrfrhQN66M/3/BVKEI='
  matrix:
    # Provide a list of GLPI version to build
    - GLPI_VERSION='' IMAGE_VARIANT=nginx-56
    - GLPI_VERSION=9.3.3 IMAGE_VARIANT=nginx-56

script:
  #
  ## Build
  #
  - ./build.sh

  #
  ## Run tests
  #
  - ./tests.sh && touch _test_ok

  #
  ## Publish
  #
  - '[ "$TRAVIS_PULL_REQUEST" == "false" ] || exit 0'
  - '[ "$TRAVIS_SECURE_ENV_VARS" == "true" -a -f _test_ok ] && ./publish.sh'
