---
language: bash

# Tell Travis to start Docker when it brings up an environment.
services:
  - docker

#env:
  # Provide a list of OSes we want to use for testing.

script:
  - export VCS_REF=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_COMMIT; else echo $TRAVIS_PULL_REQUEST_SHA; fi)
  - echo "VCS_REF"

  # 
  # Build docker image
  #
  - ${PWD}/build.sh

  #
  ## Run tests
  #
