---
language: bash

# Tell Travis to start Docker when it brings up an environment.
services:
  - docker

env:
  matrix:
    # Provide a list of GLPI version to build
    - GLPI_VERSION: ''
      DOCKERFILE_PATH: Dockerfile_nginx_56
    - GLPI_VERSION: 9.3.3
      DOCKERFILE_PATH: Dockerfile_nginx_56

script:
  #
  ## Build
  #
  - ./build.sh

  #
  ## Run tests
  #
  - ./tests.sh
