dist: xenial
language: bash
sudo: required

# Tell Travis to start Docker when it brings up an environment.
services:
  - docker

env:
  global:
    - DOCKER_REPO=wolvverine/docker-glpi
    - secure: "S7PIcphfpLTTl4DB5rh0uNDqNiJtJ3BK8qaqOaFuPScCxqNqe+5qhCGserNMm6uyfuTY2pclsLg3Ccqxjnb1EzpnRVv3q5Gdo24jlGEgtXDtrYUWw59SuTGZ+j7So1WG39fdZYdQ7OJwDTAMCdIYbWVOSV0sgw6wI3VLNn+zPoTJNXoLCyNDnB+qEvTVkZ3uwhZhQvmF4BttGnw5rSGPElbbl2zV2EzPaScuXkmD9oXKl0rtB1w/dbBe5CNq7HAAZo0FcJqKWcuYH1RbezX8qJyv/AUlmPxaB9XRjaVs7iHFvGWbfuHP3sbRaDFyZB1XPYdjkrtEzD3js0kTOiOE2IQfY97dSyXm0s+9XU7DJ05FG1rIWODO7EKg6aXak6japJQLEwRS8umh6KlA1JTgi3kmMdL2tdYbJVJYPzkYsWQcRGcGLJbvlspFlyw3M0mFsEgNiSdlAg7oeeuveF1hkR8adfl2wrUhR/bOISpVLsFnUMJRKdEs3VMpC+YZiNHnoS+XpFu/Pag3St+wHhycw5k5qfp0Ue7ca32FBNPc7BlZduiCG3dvIfdUdC8+mSQbwUkG5C/NfcgKA/JpeZvJyqIVNtEtEvAY1lqB/izKOxgpjk2HwPggGMczYj07BbdEp5R/oRlOcGDO6LM0/zL23ds5lCvlE2wWpbmB9m+5wAk="
    - secure: "ccT71NttTmV8d9oz+x22ktv//RACab8CV1hvzdC8u7VyX4jw6Ymam7blCoA86WnnR0elL618EPTvZ6Xy9jb8dlsgLz+b4NuKfktiv0cx7S1ZhMzAmSsooaarf+k5DAN0OQm9LPjEr9tPyP6WEcduKqptZWZ3ovCm+x+OEuoQnyaeiM1zi0lB7rUJwO/U0Kg4vSkr9rG+7dNwju1whXtBO0EYotpKlrK9fwQz7/HV3f8uPF0MgzudiDdigjq3+ostnfvpPb9rJ1gN/uM5EMSOOMWTJrXwtJZMvgcA6987Z7GK10fVsrUswdSuTn6z+E+A2RIUIVQwoAvr4nlsRAsZiHFXpRx7Dai3vX8jERsCeLW8UPsMWlcSw+9Cs1XUCOlSkYW672NKoFSRff7UZg36vDZj886lBspk4JHoh9iqxOpSqG7wzNMnave2BNqD8kyfPfVOl9nS8mKFH4m6jGNMTJbLsWHsYPL17kc/kLOLaXwkLWyO5volhJQvCWWaPsX+hFVZkeFhj2f2UOMzgdZ/wVv6saIEerCk2cSePzDOIOf6TKEo22am0rhgG+/l55Cx+zyIaj0M3S7hwvu1K9RwFxlh+jGaktgwFYYigrincFvZrtNagnWzdfWslyzY8fADvrYIC5a+sia0WNZLyg9gXYWEPa+UC8SvKze0oN7hpaI="
  matrix:
    # Provide a list of GLPI version to build
    - GLPI_VERSION=9.5.6 IMAGE_VARIANT=nginx-72 UPDATE_README=1 UPDATE_LATEST=1

before_install:
    - sudo apt update
    - sudo apt install -y shellcheck

script:
  #
  ## Build
  #
  - ls -l
  - ./build.sh

  #
  ## Run tests
  #
  - ./tests.sh && touch _test_ok

  #
  ## Publish
  #
  - '[ "$TRAVIS_PULL_REQUEST" == "false" ] || exit 0'
  - '[ "$TRAVIS_SECURE_ENV_VARS" == "true" -a -f _test_ok ] && ./publish.sh'
