---
language: bash

# Tell Travis to start Docker when it brings up an environment.
services:
  - docker

env:
  global:
    - DOCKER_REPO=wolvverine/docker-glpi
    - secure: 'sG4Oq4uTEMMlQNNkV6G9HNBH1bG233lxeYEFNNoeqv74C3KNOl5InRXOQsFz6dCRQX/yQ+vwBcImQsj/tf9DITKng2VtK5o3gZNPg5TPfyGWJbzfUFvX5P/HkDAm+oXSRc1ax/3Zof+hywUbVeF7H510ZeCZHoDmMSR20Q0vFqA9Zg2cQ5csV6ktm7YWqfciUXBs+J4X0obm6CI9CBwPphEWLTmF1jyMpwJ4qdeFDfhaw/Q5z73tJFsc63ePDwwLjZAHTwQ+1vFK4drzK8g7Yj6+yX0fCxXkzohIolcPSENBTIclpw3u5Pa4qeSqnQjN+tT/IfjaZXop7ICy8nvOiQvaSYL8LDCB+rO/uV/yW8lEunJRX6Yphtk/ayJyKMmR/nGFT3Euhe62EkYSF51G+1chG6dOtKcP0Qy6F+0KuTVr29/p1+vLnzH66V5bm9Tfzb03zUdQ9pnf73ukEVJoBXejgCHgWLw9/MkE/hCo4VqKovDgLtaDuy1tstfxViPnDSQCHmbiD3HflQxlxUiX6jNLg9vH8++agBFOlJqf6a+M820wUnvGHs5FX05rbYwYdpcNYOFvBzcm1v1kBo8rEmONNF1ezLo9uBFCnLWTWMzWfiIoUY4OPC2tMkgQs5hjsSbaSB+BnJPvPA+j+ZShQ6wkPYdlFMBUkLjFU/sx60I='
    - secure: 'QhiF7/Zi7E2gAuW7p8ondB/cMS5dE3Hd1356bugZgC6Tpftp5MFEgmk2ecDwJG1mvDjie8+WCdBSm7a0dumFqsUwgtO7OkHhIj3v1QZTyH1LOFNlud2Yb7r0ed6JXYte8nnmAet1sxawHB3Il6euiM7eg8FjRuB24o3PH9SUzy9xNuerhYugpS0S94EyIzEpscpyJc2c6KIkANNIKMvwf2wm3uVBQJyEwZvEjT37C97vJaBi72G/m9xKl8MfsnGmThOn4jX8kmdPue8fDtCIu2DxvfW7eEWpAKAbQf35xV8fPLrLNCjhUSimPag4YpqvWhuIqT8bBS2dyZRS57D0PV3SMKrHASUUlkd+E0p8/wkWVv4w9scOcVuKwpAL0Z3MSBtk5AXswn2smweYjgQbNQPBjcN7aVNEmZMUxKu5DXyJy5WrhyZqwmyygraWV5SP7U5spBdvs70VSWfxtgQsq1F842tus768fNEffGobcVlnrfkWkZuj1YezqeTx3skPnonCBRDVaHb/zmD9OEP2+PiDEQseKB5VBv95ZmByeSg3QtCtpZFW+wyVI75JuMki9B/6MUkJ0rPRX9Tf7cDrUXGXfywN15DDP//4i+Fb+iZLxsoMQ0/gp5oMMh4ygf7h6SJbWa7Ve4atH27gVojAYYoaVRGkgyRslf5UiYWepLk='
	
  matrix:
    # Provide a list of GLPI version to build
    # - GLPI_VERSION='' IMAGE_VARIANT=nginx-56
    - GLPI_VERSION=9.4.1.1 IMAGE_VARIANT=nginx-56

script:
  #
  ## Build
  #
  - ./build.sh

  #
  ## Run tests
  #
  - ./tests.sh && touch _test_ok

  #
  ## Publish
  #
  - '[ "$TRAVIS_PULL_REQUEST" == "false" ] || exit 0'
  - '[ "$TRAVIS_SECURE_ENV_VARS" == "true" -a -f _test_ok ] && ./publish.sh'
