---
language: bash

# Tell Travis to start Docker when it brings up an environment.
services:
  - docker

env:
  global:
    - secure: "E/Ylr8QBhrtB1sWncNMvs/deVyBY3U80COSWp2RS9gmSw7gjI8TEyFudQoPCGyq2VO1Xv37VDfG5j6Fw2jx6VKroFrmxDc8Dqcyur2AWKYTSdIsrRkBU4AAvIC3fM6oq76RdTEmkhs+iDz1rBJuyPaO2HfvtC1RsUGcUSVCrdxBzhiLK0jdZcastADikrA9gfNP3VUTAKJTFgnCUJ0xQ94Kvd/knkOp9rypiPXVDfqV4Qj6m43Ps1vsLEhmN35NrBGktB7DvFGqamhSF1v2IIuGocHLH5fqHvFihgf5tCjT43IWDBsuIvVViFln+U8PLPECMu5vj08qQnhiByOa7TIIC4wEu1uXDq6+NtVoT4XxgMgb37/ATsYQX+CMDIeD42BrpjR4P/v6IIrtXjLmaqlR1YSSE7Xd9hL3wAecKZbPppZnpRRFzF1oYXOMifAE/GHOUvNvkFGy8ZO0ZsSHQiYEGKyYxyl9jYGG0Hz78cGHI5yz5HYyjz3NvFwDr8Xs08RXSIfFag+IZGLaLza7DXLBtvSMWvGrYgv8X5eIue/UBkCJBlrrXlXTcSc/rEO98fRwX/wHz+TBl6G8XP1/smZbm8DtE3GlZda6TIGGcnLgmNM5Mh2lH5cqf7HtXWQBvzvJjK/BUwG92A4Byi68DVvDWZIQO2fwfVF4rq/LGbVQ="
    - DOCKERHUB_REGISTRY_USERNAME="wolvverine"
  matrix:
    # Provide a list of GLPI version to build
    - GLPI_VERSION=''
    - GLPI_VERSION=9.3.2

script:
  #
  ## Build
  #
  - ./hooks/build

  #
  ## Run tests
  #
  - ./tests.sh
