#!/bin/sh

set -e

basedir="${GLPI_PATHS_ROOT}"

echo 'Configuring GLPI files...'

## Remove installer
# used to remove the installer after first installation
if [ "${GLPI_REMOVE_INSTALLER}" = 'yes' ]; then
  echo 'Removing installer if needed...'
  rm -f "${basedir}/install/install.php"
fi

## Files structure
echo "Create file structure..."
for f in _cache _cron _dumps _graphs _lock _log _pictures _plugins _rss _sessions _tmp _uploads _locales; do
  dir="${basedir}/files/${f}"
  if [ ! -d "${dir}" ]; then
    mkdir -p "${dir}"
    chown www-data:www-data "${dir}"
    chmod u=rwX,g=rwX,o=--- "${dir}"
  fi
done

## Files permissions
# address issue https://github.com/Turgon37/docker-glpi/issues/2
if [ "${GLPI_CHMOD_PATHS_FILES}" = 'yes' ]; then
  echo 'Set files permissions...'
  chown -R www-data:www-data "${basedir}/files"
  chmod -R u=rwX,g=rX,o=--- "${basedir}/files"
fi

# address issue https://github.com/Turgon37/docker-glpi/issues/27
# shellcheck disable=SC2046
if [ $(stat -c %u "${basedir}/config") != $(id -u www-data) ]; then
  # shellcheck disable=SC2038
  find . -maxdepth 1 -not -name files | xargs -r chown -R www-data:www-data
fi
